enabled: true
notifications:
  - extending: 
      repository: bbaga/app-testing
      name: multirepo
    config:
      sources:
        - type: search-prs-by-reviewers
          users:
            - bbaga
            - kissanita88
